### ISSUE TITLE
Add the Table of contents to the subsections to the Part 13 in Lessons

### ISSUE THREAD

**Issue by rcallaby** [rcallaby/Learn-Git#111]
# New Issue

## What can be improved?
A table of contents to the top of the page listing all of the subsections in this part 13 where the table of contents are linked to allow for easier navigation

**Comment by bkpecho** [comment]
Hello. Can you assign this to me? I would like to work on this issue.

**Comment by rcallaby** [comment]
@bkpecho It is all yours
