### ISSUE TITLE
Add Images to Contributing.md file

### ISSUE THREAD

**Issue by rcallaby** [rcallaby/Learn-Git#126]
**Is your feature request related to a problem? Please describe.**
Add Images to the Contributing.md file so to make it easier to understand. Basically, like in the README and First Contributions file adding images would help break up the tutorial and make it easier to understand.

**Describe the solution you'd like**
Add Screenshots of the Process described how to add your contribution to this git repository.

**Comment by harshil-junakiya** [comment]
Hey @rcallaby ,
Can you assign me this issue?

**Comment by rcallaby** [comment]
@harshil-junakiya It is all yours now

**Comment by rcallaby** [comment]
@harshil-junakiya Any progress on this?

**Comment by harshil-junakiya** [comment]
I will send PR by tonight
