### ISSUE TITLE
Github Action - Check for broken links

### ISSUE THREAD

**Issue by rcallaby** [rcallaby/Learn-Git#142]
**Is your feature request related to a problem? Please describe.**
Yes, I want to add a github action that is activated daily that will automatically check for broken links. 

**Describe the solution you'd like**
A Github action yaml file created with a cron job that runs every day and checks for broken links in the repository

**Describe alternatives you've considered**
The only other alternative, which isn't ideal is to review every single link and that is just not feasible.

**Comment by sdesani** [comment]
If its not taken, can you assign this to me ?

**Comment by sdesani** [comment]
PR which resolves this issue - https://github.com/rcallaby/Learn-Git/pull/147
