### ISSUE TITLE
Consolidate the Images folder

### ISSUE THREAD

**Issue by rcallaby** [rcallaby/Learn-Git#152]
### What is the issue?

At present there are two image folders, in order to streamline the repository it would be helpful to keep all images in one folder with subfolders that logically separate the images based upon the parts of the lessons that they apply to.

### How can this be fixed?
All images could be put into the /images folder with subfolders for different parts of the repository. For instance the readme images could be in the /images/readme folder and so on.

**Comment by frantic-rabbit** [comment]
Hey @rcallaby, i want to work on this. Can you please assign it to me?
