### ISSUE TITLE
Update the directory structure of Lessons to accommodate multiple languages

### ISSUE THREAD

**Issue by rcallaby** [rcallaby/Learn-Git#216]
### What is needed?

Essentially, the current directory structure of the repository doesn't accommodate multiple languages. This needs to change so that all English lessons are in a folder underneath the folder Lessons with the folder name en and the currently in progress translation to simplified Chinese is in a folder named zh-CN so that it looks like the following:

Lessons
   en
   zh-CN

Obviously the links to the images would need to be updated as well as the links in the readme.md file.

**Comment by JayOaks** [comment]
Hi,
Can I try working on this?

**Comment by rcallaby** [comment]
@JayOaks Sure thing

**Comment by JayOaks** [comment]
Thanks.

**Comment by JayOaks** [comment]
I have created the pull request @rcallaby

**Comment by rcallaby** [comment]
@JayOaks I noticed that, thank you very much for your contributions.
