### ISSUE TITLE
Fix the Table of Contents in Readme.md file so that the links actually work

### ISSUE THREAD

**Issue by rcallaby** [rcallaby/Learn-Git#219]
### What is needed?

Since the file structure was changed the Table of Contents in the readme.md file is out of sync with the contents of the Lessons. Essentially, the default language of the repository is English and the default Table of Contents is English so it should point to the English contents.

The linked TOC needs to be updated so that each link in the default Readme.md file points to the English (en) contents.

**Comment by ibzimh** [comment]
Can I be assigned to this?

**Comment by rcallaby** [comment]
@ibzimh Yes you can

**Comment by ibzimh** [comment]
I've made a PR for the links, Is there something else that needs to be done? The links are working by the way.
