### ISSUE TITLE
Translate Contributing.md into Hindi

### ISSUE THREAD

**Issue by rcallaby** [rcallaby/Learn-Git#226]
### What is needed?

Essentially, I am looking for a native Hindi speaker to translate the contributing.md file of the repository into Hindi.  As I am trying to reach more people you may be asked to become a collaborator on this project so that you can handle any issues in Hindi. This is more than just a one-off translation job.

**Comment by Rajiv-paul** [comment]
Hey! @rcallaby can we get connect on LinkedIn

**Comment by rcallaby** [comment]
@Rajiv-paul Sure, send an invite there

**Comment by Rajiv-paul** [comment]
Already done ✅

**Comment by Rajiv-paul** [comment]
should I create folder for Hindi contributing.md file?

**Comment by rcallaby** [comment]
No, it should reside in the same place as the default (English) contibuting.md file

**Comment by Rajiv-paul** [comment]
how should I name it?

**Comment by rcallaby** [comment]
contributing_hi.md

**Comment by Rajiv-paul** [comment]
ok sure

**Comment by rcallaby** [comment]
Actually, the contributing_hi.md was blank can you please correct this?

**Comment by Rajiv-paul** [comment]
@rcallaby already rectified 😅
