### ISSUE TITLE
Translate Part 00 into Simplified Chinese

### ISSUE THREAD

**Issue by rcallaby** [rcallaby/Learn-Git#233]

**Comment by rcallaby** [comment]
@wuyu-wy Feel free to assign yourself any tasks you're able to do.

**Comment by wuyu-wy** [comment]
Okay, the school has been busy working on software projects lately，I will do it in my free time，maybe a few days later.

**Comment by rcallaby** [comment]
@wuyu-wy Not sure what your schedule is right now but any help would be greatly appreciated!
