### ISSUE TITLE
Translate Part 3 of the Lessons into Russian

### ISSUE THREAD

**Issue by rcallaby** [rcallaby/Learn-Git#315]

**Comment by AMiracle-creator** [comment]
Hi, I can do this, I'll be happy to help.

**Comment by rcallaby** [comment]
@AMiracle-creator Okay I will assign this to you.

**Comment by rcallaby** [comment]
@AMiracle-creator I hate that I have to ask this. Any progress on this?

**Comment by AMiracle-creator** [comment]
@rcallaby I apologize for such a delay, I was very busy, I’ll get started now

**Comment by AMiracle-creator** [comment]
I created pull request, please check it out

**Comment by rcallaby** [comment]
@ AMiracle-creator  If you wish you're certainly welcome to contribute more if you have the time and energy to do so.
