### ISSUE TITLE
Translate part 1 to Mongolian

### ISSUE THREAD

**Issue by Munkhtur** [rcallaby/Learn-Git#437]

**Comment by rcallaby** [comment]
Do you know Mongolian? Or know someone who does? @Munkhtur

**Comment by Munkhtur** [comment]
I do. I started working on the part 00

**Comment by rcallaby** [comment]
Please make sure you submit a separate pull request for each part of the translation. Meaning Part 1 would be separate from Part 00. It helps keep pull requests smaller and makes it easier to review them.

**Comment by Munkhtur** [comment]
Got it
