### ISSUE TITLE
Translate CONTRIBUTING.md to Mongolian

### ISSUE THREAD

**Issue by rcallaby** [rcallaby/Learn-Git#450]

**Comment by Munkhtur** [comment]
Should I create a new branch and delete the accepted branch every time I make pull request?

**Comment by rcallaby** [comment]
Yes, a differently named branch for each separate pull request. I actually routinely do this on my own repositories so that I can track the changes.

**Comment by rcallaby** [comment]
@Munkhtur It has been awhile, are you doing okay?

**Comment by Munkhtur** [comment]
Yeah. Got busy with other work. I'm not when I'll get back to it.
