### ISSUE TITLE
Translate the French titles of the French lessons so that they are in French

### ISSUE THREAD

**Issue by rcallaby** [rcallaby/Learn-Git#621]

**Comment by rcallaby** [comment]
Please make sure this is done before syncing the readme file issue.

**Comment by hugodel07** [comment]
Hello ! I'd like to do it this week-end as my first contribution :) Is there any more that I should know other than what's already in the `firstcontribution.md` file ?

**Comment by rcallaby** [comment]
All you need to do is what it says in the title of the issue. So basically translate the lesson titles and the individual markdown files so that they are all translated to their french titles. If you need more clarification please feel free to ask.
