### ISSUE TITLE
Misassignment of Language: "Malay" Instead of "Malayalam"

### ISSUE THREAD

**Issue by adilnvm** [rcallaby/Learn-Git#723]
### MALAY ≠ MALAYALAM

This is NOT a technical bug but rather a **_misunderstanding_** .

Malay is a language spoken in Malaysia and Indonesia, while Malayalam is a Dravidian language primarily spoken in the Indian state of Kerala. They belong to different language families and regions.

As @rcallaby has  : 
Assigned translation work is for the **Malay language,** but it was supposed to be for the **Malayalam language**. This assignment error occurred due to a mix-up between the two languages, which are **distinct** from each other.
https://github.com/rcallaby/Learn-Git/pull/697
[![image](https://github.com/user-attachments/assets/b48e88bc-b31d-460a-aa75-f7dd716030d5)]

**Expected behavior**
The task should be reassigned or updated to reflect that the translation needs to be done in Malayalam, not Malay. The correct language needs to be specified to avoid further confusion and ensure that the translations align with the intended audience.

**Screenshots**

![image](https://github.com/user-attachments/assets/ff29f0a4-1e05-43f8-96f1-59dc06f5fedd)
![image](https://github.com/user-attachments/assets/444974d8-f1d5-4167-aa8b-79c5ad411f64)
![image](https://github.com/user-attachments/assets/c93fea1b-88ae-4808-a240-60c2182ca91c)

**Additional context**
It should be "Malayalam" instead of "Malay" as they are very Different languages spoken thousands of miles apart.
and hence create a confusion
thankyou for addressing this issue

**Comment by rcallaby** [comment]
Edited all issues to correct this misunderstanding.
