### ISSUE TITLE
Add Links to the Table of Contents for Part 01

### ISSUE THREAD

**Issue by rcallaby** [rcallaby/Learn-Git#80]
# New Issue

## What is needed?
I need a linked table of contents for this section. Essentially, I need this section to look like the following section:

https://github.com/rcallaby/Learn-Git/blob/main/Lessons/Part-00-History-and-Foundations/historyofgit.md

Of course, I need the subject headers to be maintained but I just need them to be linked.

Please link this issue to your pull request so that when I approve it then it will automatically close the ticket.

**Comment by TFM-HITESH** [comment]
Hey, can I be assigned this issue ? I can also work on implementing links for the other sections, as well as fixing the broken links in the README.md file too. This is the first issue I am solving on my GitHub profile and I really look forward to helping out with such a comprehensive guide about learning git and GitHub !

**Comment by rcallaby** [comment]
All yours

**Comment by TFM-HITESH** [comment]
Thank you very much. Will make the PR upon the commencement of Hacktoberfest

**Comment by rcallaby** [comment]
Please make sure you just stick to the assigned task. If you find another issue feel free to create one.

**Comment by TFM-HITESH** [comment]
Understood, Thank you

**Comment by TFM-HITESH** [comment]
Hey, it seems as though I closed my PR by accident. Can I resubmit it please ?

**Comment by rcallaby** [comment]
I reopened it and merged it, no need to resubmit.
