### ISSUE TITLE
Add Links to the Table of Contents to Part 02

### ISSUE THREAD

**Issue by rcallaby** [rcallaby/Learn-Git#81]
# New Issue

## What is needed.

I need the table of contents of Part 02 to look like this:

https://github.com/rcallaby/Learn-Git/blob/main/Lessons/Part-00-History-and-Foundations/historyofgit.md

Please link this issue to your pull request so that it will automatically close this ticket when the pull request has been approved

**Comment by TFM-HITESH** [comment]
Hey, can I be assigned this issue ? I can also work on implementing links for the other sections, as well as fixing the broken links in the README.md file too. This is the first issue I am solving on my GitHub profile and I really look forward to helping out with such a comprehensive guide about learning git and GitHub !

I would like to make this contribution as a participant in the upcoming Hacktoberfest 23 :)

**Comment by rcallaby** [comment]
It is all yours

**Comment by TFM-HITESH** [comment]
Thank you very much ! Will make the PR as soon as Hacktoberfest begins :)

**Comment by rcallaby** [comment]
Please just stick to the assigned task. Do not fix anything beyond the scope of this issue. IF you find a broken link, create an issue and I can either assign it to you or someone else who is also participating in the hacktoberfest.

**Comment by TFM-HITESH** [comment]
Understood. Thank you !
