### ISSUE TITLE
Add Links to the Table of Contents to Part 04 in Lessons

### ISSUE THREAD

**Issue by rcallaby** [rcallaby/Learn-Git#84]
# New Issue

## What can be improved?
A Table of contents with links to the subsections to improved navigation

**Comment by himanegi** [comment]
Hey, I'd like to work in this issue.

**Comment by himanegi** [comment]
Have solved issue https://github.com/rcallaby/Learn-Git/issues/84 and have added the required links to the table of contents. It navigates properly to respective sections upon clicking. Can you review it ?
