### ISSUE TITLE
Issue with Broken Links in README.md

### ISSUE THREAD

**Issue by TFM-HITESH** [rcallaby/Learn-Git#86]
**Describe the bug**
In the README.md file, many of the links are broken. Some are pointing to file names which are incorrectly spelt, or they are pointing to the legacy naming of the files, which do not exist anymore. 

**Required Fix**
To go through the README.md file and fix all the broken links and make them point to the correct file urls to fix the broken links.

**Comment by rcallaby** [comment]
Feel free to fix this issue when you have the time.

**Comment by TFM-HITESH** [comment]
I will, thank you !

**Comment by TFM-HITESH** [comment]
May I rename the files to have the same structure throughout the codebase ?

For eg :

Renaming "historyofgit.md" to "history-of-git.md", also to give more descriptive names to files named "outline.md"

**Comment by TFM-HITESH** [comment]
Hey, just created a PR to fix this issue :)
