### ISSUE TITLE
Images with Lessons

### ISSUE THREAD

**Issue by TFM-HITESH** [rcallaby/Learn-Git#96]
Each tutorial will be greatly improved if implemented with images to break the monotony of reading walls of text.

**Comment by rcallaby** [comment]
I agree. It could be improved with this enhancement. I will assign this one to you.

**Comment by TFM-HITESH** [comment]
Will slowly work on this over time

**Comment by rcallaby** [comment]
One important note. Please make sure you have the copyright to use images in this repository, either by creating them yourself or finding appropriate royalty free public domain images.

**Comment by rcallaby** [comment]
I also added myself to this
